apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: go-web-app
  namespace: flux-system
spec:
  image: ibnuislamy/go-web-app
  interval: 30s
  secretRef:
    name: dockerhub-key

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: go-web-app
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: go-web-app
  policy:
    semver:
      range: '>=0.0.1'

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-app
  namespace: playground-dfgjkt
  labels:
    app: go-web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-web-app
  template:
    metadata:
      labels:
        app: go-web-app
    spec:
      containers:
      - name: go-web-app
        image: ibnuislamy/go-web-app:1.0.3 # {"$imagepolicy": "flux-system:go-web-app"}
        ports:
        - containerPort: 8080
        envFrom:
          - secretRef:
              name: "go-secret"

---
apiVersion: v1
kind: Service
metadata:
  name: go-web-app
  namespace: playground-dfgjkt
  labels:
    app: go-web-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: go-web-app

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-web-app
  namespace: playground-dfgjkt
spec:
  rules:
    - host: api.dwyor.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: go-web-app
                port:
                  number: 80
  ingressClassName: traefik